/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author FDLY
 */
public class Bayar extends javax.swing.JFrame {

    /**
     * Creates new form Bayar
     */
    public Bayar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ringk_Bel = new javax.swing.JLabel();
        Det_Pemb = new javax.swing.JLabel();
        Tot_Harg = new javax.swing.JLabel();
        Nama_Pemb = new javax.swing.JLabel();
        edtNama_Pemb = new javax.swing.JTextField();
        Ongkir1 = new javax.swing.JLabel();
        Email_Pemb = new javax.swing.JLabel();
        edtEmail_Pemb = new javax.swing.JTextField();
        Method_Pemb = new javax.swing.JLabel();
        Telp_Pemb = new javax.swing.JLabel();
        bts = new javax.swing.JButton();
        btncod = new javax.swing.JButton();
        Alamat_Peng = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtAlamat_Peng = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ringk_Bel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Ringk_Bel.setText("Ringkasan Belanjaan");
        getContentPane().add(Ringk_Bel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        Det_Pemb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Det_Pemb.setText("DETAIL PEMBELI");
        getContentPane().add(Det_Pemb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        Tot_Harg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Tot_Harg.setText("Total Harga");
        getContentPane().add(Tot_Harg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        Nama_Pemb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Nama_Pemb.setText("Nama Pembeli");
        getContentPane().add(Nama_Pemb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        getContentPane().add(edtNama_Pemb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, -1));

        Ongkir1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Ongkir1.setText("Ongkos Kirim");
        getContentPane().add(Ongkir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        Email_Pemb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Email_Pemb.setText("Email Pembeli");
        getContentPane().add(Email_Pemb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        getContentPane().add(edtEmail_Pemb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 100, -1));

        Method_Pemb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Method_Pemb.setText("Metode Pembayaran");
        getContentPane().add(Method_Pemb, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        Telp_Pemb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Telp_Pemb.setText("Telepon/Handphone");
        getContentPane().add(Telp_Pemb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        bts.setText("Transfer");
        bts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsActionPerformed(evt);
            }
        });
        getContentPane().add(bts, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 90, -1));

        btncod.setText("COD");
        getContentPane().add(btncod, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 90, -1));

        Alamat_Peng.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Alamat_Peng.setText("Alamat Pengiriman");
        getContentPane().add(Alamat_Peng, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        edtAlamat_Peng.setColumns(20);
        edtAlamat_Peng.setRows(5);
        jScrollPane1.setViewportView(edtAlamat_Peng);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsActionPerformed

    }//GEN-LAST:event_btsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bayar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat_Peng;
    private javax.swing.JLabel Det_Pemb;
    private javax.swing.JLabel Email_Pemb;
    private javax.swing.JLabel Method_Pemb;
    private javax.swing.JLabel Nama_Pemb;
    private javax.swing.JLabel Ongkir1;
    private javax.swing.JLabel Ringk_Bel;
    private javax.swing.JLabel Telp_Pemb;
    private javax.swing.JLabel Tot_Harg;
    private javax.swing.JButton btncod;
    private javax.swing.JButton bts;
    private javax.swing.JTextArea edtAlamat_Peng;
    private javax.swing.JTextField edtEmail_Pemb;
    private javax.swing.JTextField edtNama_Pemb;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
