/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package koperasiproduk;

/**
 *
 * @author FDLY
 */
public class Pembayaran extends javax.swing.JFrame {

    /**
     * Creates new form Pembayaran
     */
    public Pembayaran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Det_Pemb = new javax.swing.JLabel();
        Nama_Pemb = new javax.swing.JLabel();
        edtNama_Pemb = new javax.swing.JTextField();
        Email_Pemb = new javax.swing.JLabel();
        edtEmail_Pemb = new javax.swing.JTextField();
        Telp_Pemb = new javax.swing.JLabel();
        edtTelp_Pemb = new javax.swing.JTextField();
        Alamat_Peng = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtAlamat_Peng = new javax.swing.JTextArea();
        Ringk_Bel = new javax.swing.JLabel();
        Tot_Harg = new javax.swing.JLabel();
        Tot_Harg1 = new javax.swing.JLabel();
        Ongkir1 = new javax.swing.JLabel();
        Ongkir = new javax.swing.JLabel();
        Method_Pemb = new javax.swing.JLabel();
        cbPemb_CashOf = new javax.swing.JCheckBox();
        btnPemb_Transfer = new javax.swing.JCheckBox();
        btnPemb_COD = new javax.swing.JCheckBox();
        btnPemb_Cashbon = new javax.swing.JCheckBox();
        btnProses = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Det_Pemb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Det_Pemb.setText("DETAIL PEMBELI");

        Nama_Pemb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Nama_Pemb.setText("Nama Pembeli");

        Email_Pemb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Email_Pemb.setText("Email Pembeli");

        Telp_Pemb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Telp_Pemb.setText("Telepon/Handphone");

        edtTelp_Pemb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtTelp_PembActionPerformed(evt);
            }
        });

        Alamat_Peng.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Alamat_Peng.setText("Alamat Pengiriman");

        edtAlamat_Peng.setColumns(20);
        edtAlamat_Peng.setRows(5);
        jScrollPane1.setViewportView(edtAlamat_Peng);

        Ringk_Bel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Ringk_Bel.setText("Ringkasan Belanjaan");

        Tot_Harg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Tot_Harg.setText("Total Harga");

        Tot_Harg1.setText("Label Buat Harga");

        Ongkir1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Ongkir1.setText("Ongkos Kirim");

        Ongkir.setText("Label Buat Ongkir");

        Method_Pemb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Method_Pemb.setText("Metode Pembayaran");

        cbPemb_CashOf.setText("Cash On Office");

        btnPemb_Transfer.setText("Transfer");

        btnPemb_COD.setText("Cash On Delivery");

        btnPemb_Cashbon.setText("CashBon");

        btnProses.setText("Proses Pembelian");

        btnClear.setText("Clear");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 40, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Det_Pemb)
                            .addGap(112, 112, 112)
                            .addComponent(Ringk_Bel))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Nama_Pemb)
                            .addGap(184, 184, 184)
                            .addComponent(Tot_Harg)
                            .addGap(19, 19, 19)
                            .addComponent(Tot_Harg1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(edtNama_Pemb, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)
                            .addComponent(Ongkir1)
                            .addGap(6, 6, 6)
                            .addComponent(Ongkir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Email_Pemb)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(edtEmail_Pemb, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)
                            .addComponent(Method_Pemb))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Telp_Pemb)
                            .addGap(153, 153, 153)
                            .addComponent(cbPemb_CashOf))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(edtTelp_Pemb, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)
                            .addComponent(btnPemb_Transfer))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Alamat_Peng)
                            .addGap(159, 159, 159)
                            .addComponent(btnPemb_COD))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnPemb_Cashbon)
                                .addComponent(btnProses))
                            .addGap(18, 18, 18)
                            .addComponent(btnClear)))
                    .addGap(0, 41, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 43, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Det_Pemb)
                        .addComponent(Ringk_Bel))
                    .addGap(12, 12, 12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Nama_Pemb)
                        .addComponent(Tot_Harg)
                        .addComponent(Tot_Harg1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(12, 12, 12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(edtNama_Pemb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Ongkir1)
                                .addComponent(Ongkir))))
                    .addGap(8, 8, 8)
                    .addComponent(Email_Pemb)
                    .addGap(12, 12, 12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(edtEmail_Pemb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(Method_Pemb)))
                    .addGap(12, 12, 12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(Telp_Pemb))
                        .addComponent(cbPemb_CashOf))
                    .addGap(7, 7, 7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(edtTelp_Pemb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(btnPemb_Transfer)))
                    .addGap(12, 12, 12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(Alamat_Peng))
                        .addComponent(btnPemb_COD))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(btnPemb_Cashbon)
                                    .addGap(35, 35, 35)
                                    .addComponent(btnProses))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(61, 61, 61)
                                    .addComponent(btnClear)))
                            .addGap(0, 58, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtTelp_PembActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtTelp_PembActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtTelp_PembActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat_Peng;
    private javax.swing.JLabel Det_Pemb;
    private javax.swing.JLabel Email_Pemb;
    private javax.swing.JLabel Method_Pemb;
    private javax.swing.JLabel Nama_Pemb;
    private javax.swing.JLabel Ongkir;
    private javax.swing.JLabel Ongkir1;
    private javax.swing.JLabel Ringk_Bel;
    private javax.swing.JLabel Telp_Pemb;
    private javax.swing.JLabel Tot_Harg;
    private javax.swing.JLabel Tot_Harg1;
    private javax.swing.JButton btnClear;
    private javax.swing.JCheckBox btnPemb_COD;
    private javax.swing.JCheckBox btnPemb_Cashbon;
    private javax.swing.JCheckBox btnPemb_Transfer;
    private javax.swing.JButton btnProses;
    private javax.swing.JCheckBox cbPemb_CashOf;
    private javax.swing.JTextArea edtAlamat_Peng;
    private javax.swing.JTextField edtEmail_Pemb;
    private javax.swing.JTextField edtNama_Pemb;
    private javax.swing.JTextField edtTelp_Pemb;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
