/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package koperasiproduk;

/**
 *
 * @author HP
 */
public class PengelolaanPembayaran extends javax.swing.JFrame {

    /**
     * Creates new form PengelolaanPembayaran
     */
    public PengelolaanPembayaran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Det_Pemb = new javax.swing.JLabel();
        Nama_Pemb = new javax.swing.JLabel();
        edtNama_Pemb = new javax.swing.JTextField();
        Email_Pemb = new javax.swing.JLabel();
        edtEmail_Pemb = new javax.swing.JTextField();
        Telp_Pemb = new javax.swing.JLabel();
        edtTelp_Pemb = new javax.swing.JTextField();
        Alamat_Peng = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtAlamat_Peng = new javax.swing.JTextArea();
        Ringk_Bel = new javax.swing.JLabel();
        Tot_Harg = new javax.swing.JLabel();
        Tot_Harg1 = new javax.swing.JLabel();
        Ongkir1 = new javax.swing.JLabel();
        Ongkir = new javax.swing.JLabel();
        Method_Pemb = new javax.swing.JLabel();
        cbPemb_CashOf = new javax.swing.JCheckBox();
        btnPemb_Transfer = new javax.swing.JCheckBox();
        btnPemb_COD = new javax.swing.JCheckBox();
        btnPemb_Cashbon = new javax.swing.JCheckBox();
        btnProses = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Det_Pemb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Det_Pemb.setText("DETAIL PEMBELI");
        getContentPane().add(Det_Pemb, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        Nama_Pemb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Nama_Pemb.setText("Nama Pembeli");
        getContentPane().add(Nama_Pemb, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 40, -1, -1));
        getContentPane().add(edtNama_Pemb, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 69, 205, -1));

        Email_Pemb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Email_Pemb.setText("Email Pembeli");
        getContentPane().add(Email_Pemb, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 105, -1, -1));
        getContentPane().add(edtEmail_Pemb, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 134, 205, -1));

        Telp_Pemb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Telp_Pemb.setText("Telepon/Handphone");
        getContentPane().add(Telp_Pemb, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 175, -1, -1));

        edtTelp_Pemb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtTelp_PembActionPerformed(evt);
            }
        });
        getContentPane().add(edtTelp_Pemb, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 199, 205, -1));

        Alamat_Peng.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Alamat_Peng.setText("Alamat Pengiriman");
        getContentPane().add(Alamat_Peng, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 240, -1, -1));

        edtAlamat_Peng.setColumns(20);
        edtAlamat_Peng.setRows(5);
        jScrollPane1.setViewportView(edtAlamat_Peng);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 263, 205, -1));

        Ringk_Bel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Ringk_Bel.setText("Ringkasan Belanjaan");
        getContentPane().add(Ringk_Bel, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 6, -1, -1));

        Tot_Harg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Tot_Harg.setText("Total Harga");
        getContentPane().add(Tot_Harg, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 40, -1, -1));

        Tot_Harg1.setText("Label Buat Harga");
        getContentPane().add(Tot_Harg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 40, 120, 17));

        Ongkir1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Ongkir1.setText("Ongkos Kirim");
        getContentPane().add(Ongkir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 75, -1, -1));

        Ongkir.setText("Label Buat Ongkir");
        getContentPane().add(Ongkir, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 75, 120, -1));

        Method_Pemb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Method_Pemb.setText("Metode Pembayaran");
        getContentPane().add(Method_Pemb, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 136, -1, -1));

        cbPemb_CashOf.setText("Cash On Office");
        getContentPane().add(cbPemb_CashOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 174, -1, -1));

        btnPemb_Transfer.setText("Transfer");
        getContentPane().add(btnPemb_Transfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 204, -1, -1));

        btnPemb_COD.setText("Cash On Delivery");
        getContentPane().add(btnPemb_COD, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 239, -1, -1));

        btnPemb_Cashbon.setText("CashBon");
        getContentPane().add(btnPemb_Cashbon, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 265, -1, -1));

        btnProses.setText("Proses Pembelian");
        getContentPane().add(btnProses, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 318, -1, -1));

        btnClear.setText("Clear");
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 318, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtTelp_PembActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtTelp_PembActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtTelp_PembActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PengelolaanPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PengelolaanPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PengelolaanPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PengelolaanPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PengelolaanPembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat_Peng;
    private javax.swing.JLabel Det_Pemb;
    private javax.swing.JLabel Email_Pemb;
    private javax.swing.JLabel Method_Pemb;
    private javax.swing.JLabel Nama_Pemb;
    private javax.swing.JLabel Ongkir;
    private javax.swing.JLabel Ongkir1;
    private javax.swing.JLabel Ringk_Bel;
    private javax.swing.JLabel Telp_Pemb;
    private javax.swing.JLabel Tot_Harg;
    private javax.swing.JLabel Tot_Harg1;
    private javax.swing.JButton btnClear;
    private javax.swing.JCheckBox btnPemb_COD;
    private javax.swing.JCheckBox btnPemb_Cashbon;
    private javax.swing.JCheckBox btnPemb_Transfer;
    private javax.swing.JButton btnProses;
    private javax.swing.JCheckBox cbPemb_CashOf;
    private javax.swing.JTextArea edtAlamat_Peng;
    private javax.swing.JTextField edtEmail_Pemb;
    private javax.swing.JTextField edtNama_Pemb;
    private javax.swing.JTextField edtTelp_Pemb;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
